source "https://rubygems.org"

gem "cinch", "~>2.0.9"
gem "httparty", "~>0.9"
gem "redis", "~>3.0.6"
gem "nokogiri"
gem "rspec", "~>2.13.0", :group => "dev"
gem "fakeredis", "~>0.4.2", :group => "dev"
gem "foreman", "~>0.63.0", :group => "dev"
gem "pp"
gem "pdf-reader"
gem "marky_markov"
gem "parallel"
gem "elasticsearch"
